import { Idol } from './types';

export const IDOLS: Idol[] = [
  {
    id: 'nayeon',
    name: 'Nayeon',
    role: 'Lead Vocal, Center & Soloist',
    personality: 'The iconic "Bunny" of Twice. Bright, confident, and energetic solo star who loves her fans dearly.',
    personalityTag: 'Pop! Star',
    image: 'https://legacy.kpopping.com/67/4/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-3.jpeg',
    voiceIntro: 'You want to see my solo performance? Let\'s go!',
    hobbies: ['Watching movies', 'Finding good restaurants', 'Solo travel'],
    favoriteFood: 'Marinated Crabs & Jello',
    difficulty: 5,
  },
  {
    id: 'jeongyeon',
    name: 'Jeongyeon',
    role: 'Lead Vocal & Guardian',
    personality: 'The charismatic "Girl Crush" of Twice. Known for her maturity and caring nature, she is the emotional anchor who keeps everyone grounded.',
    personalityTag: 'Guardian Girl Crush',
    image: 'https://legacy.kpopping.com/13/5/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-5.jpeg',
    voiceIntro: 'Don\'t worry about the noise. I\'m right here by your side.',
    hobbies: ['Lego building', 'Running', 'Cleaning and organizing'],
    favoriteFood: 'Golbangi Muchim (Sea Snail Salad)',
    difficulty: 7,
  },
  {
    id: 'momo',
    name: 'Momo',
    role: 'Main Dancer, Rapper & Vocalist',
    personality: 'Twice\'s "Dancing Machine." A powerful performer with a pure, innocent personality off-stage and a deep love for food.',
    personalityTag: 'Dancing Machine',
    image: 'https://legacy.kpopping.com/e5/4/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-7.jpeg',
    voiceIntro: 'Did you see me dance today? I worked really hard... can we eat now?',
    hobbies: ['Eating', 'Looking at pictures of food', 'Dancing', 'Shopping'],
    favoriteFood: 'Jokbal (Pig\'s Trotters)',
    difficulty: 6,
  },
  {
    id: 'sana',
    name: 'Sana',
    role: 'Sub Vocalist & MiSaMo Member',
    personality: 'Twice\'s "Cutie-Sexy" representative. Incredibly optimistic, clumsy, and affectionate. She famously coined the phrase "No Sana, No Life."',
    personalityTag: 'No Sana No Life',
    image: 'https://legacy.kpopping.com/4c/5/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-9.jpeg',
    voiceIntro: 'Shy shy shy... oh! You caught me staring at you again, didn\'t you?',
    hobbies: ['Collecting perfumes', 'Shopping', 'Eating luxurious snacks'],
    favoriteFood: 'Spicy Food & Yogurt Smoothies',
    difficulty: 4,
  },
  {
    id: 'jihyo',
    name: 'Jihyo',
    role: 'Leader, Main Vocal & Soloist',
    personality: 'Twice\'s dependable leader who trained for 10 years. Known for her powerful vocals and "God-tier" work ethic. She debuted as a soloist with the album "Zone."',
    personalityTag: 'God Jihyo',
    image: 'https://legacy.kpopping.com/c3/3/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-11.jpeg',
    voiceIntro: 'After ten years of waiting... I\'m finally here with you. Ready to start?',
    hobbies: ['Surfing', 'Pilates', 'Swimming', 'Online gaming'],
    favoriteFood: 'Smoothies & Milk Tea',
    difficulty: 6,
  },
  {
    id: 'mina',
    name: 'Mina',
    role: 'Main Dancer, Vocalist & MiSaMo Member',
    personality: 'Twice\'s "Black Swan." After 11 years of ballet training, she brings a unique elegance to the group. Known for her quiet, intelligent, and introverted charm.',
    personalityTag: 'Black Swan',
    image: 'https://legacy.kpopping.com/01/1/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-13.jpeg',
    voiceIntro: 'Do you want to play a game together? Or maybe just some quiet time...',
    hobbies: ['Gaming (Minecraft)', 'Ballet', 'Knitting', 'Puzzles'],
    favoriteFood: 'Yukhoe & Ketchup',
    difficulty: 8,
  },
  {
    id: 'dahyun',
    name: 'Dahyun',
    role: 'Lead Rapper & Sub Vocalist',
    personality: 'Twice\'s "Eagle Dancer" with a legendary ability to find any camera. Known for her "Dubu" (Tofu) fair skin, incredible flexibility, and wit as a variety show star.',
    personalityTag: 'Camera-Finding Dubu',
    image: 'https://legacy.kpopping.com/12/0/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-15.jpeg',
    voiceIntro: 'Found you! You can\'t hide from my camera eyes. Want to see a tofu dance?',
    hobbies: ['Playing piano', 'Songwriting', 'Spotting cameras', 'Smiling'],
    favoriteFood: 'Chocolate & Bread',
    difficulty: 5,
  },
  {
    id: 'chaeyoung',
    name: 'Chaeyoung',
    role: 'Main Rapper & Sub Vocalist',
    personality: 'Twice\'s "Baby Beast." A free-spirited artist who expresses her unique worldview through drawing, poetry, and songwriting. She is one of the group\'s most prolific songwriters.',
    personalityTag: 'Strawberry Princess',
    image: 'https://legacy.kpopping.com/6e/3/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-17.jpeg',
    voiceIntro: 'Do you want to see my sketches? I put a lot of my heart into them, just like I do with you.',
    hobbies: ['Drawing', 'Songwriting', 'Poetry', 'Listening to indie music'],
    favoriteFood: 'Strawberries & Pasta',
    difficulty: 5,
  },
  {
    id: 'tzuyu',
    name: 'Tzuyu',
    role: 'Lead Dancer, Sub Vocalist & Soloist',
    personality: 'Twice\'s "Visual Queen" and solo artist. Known for her graceful presence, honesty, and calm demeanor. Often called the "Savage Maknae" for her blunt but adorable wit.',
    personalityTag: 'Visual Savage Maknae',
    image: 'https://legacy.kpopping.com/cf/1/TWICE-Special-Album-TEN-The-Story-Goes-On-Concept-Photos-documents-19.jpeg',
    voiceIntro: 'Is it okay if I\'m honest? I really enjoyed spending time with you today.',
    hobbies: ['Listening to music', 'Playing with dogs', 'Traveling', 'Watching performances'],
    favoriteFood: 'Kimbap & Eel',
    difficulty: 7,
  }
];